-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public."Usuario"
(
    id_usuario serial NOT NULL,
    nombre text,
    apellido text,
    email text NOT NULL,
    "contraseña" text,
    pic_url text,
    rol text,
    fecha_registro time without time zone DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id_usuario)
);

CREATE TABLE IF NOT EXISTS public.profesional
(
    id_profesional serial NOT NULL,
    descripcion text,
    experiencia text,
    habilidades text,
    calificacion_promedio double precision,
    suscripcion_premium boolean,
    PRIMARY KEY (id_profesional)
);

CREATE TABLE IF NOT EXISTS public.servicio
(
    id_servicio serial NOT NULL,
    id_profesional serial,
    titulo text,
    descripcion text,
    precio integer,
    tiempo_entrega integer,
    estado text,
    destacado boolean,
    PRIMARY KEY (id_servicio)
);

CREATE TABLE IF NOT EXISTS public."Pedido"
(
    id_pedido serial,
    id_servicio serial,
    id_cliente serial,
    fecha_contratacion time without time zone,
    estado text,
    archivo_entraga text,
    PRIMARY KEY (id_pedido)
);

CREATE TABLE IF NOT EXISTS public.pago
(
    id_pago serial,
    id_pedido serial,
    monto integer,
    fecha_pago time without time zone,
    metodo_pago text,
    estado text,
    PRIMARY KEY (id_pago)
);

CREATE TABLE IF NOT EXISTS public."reseñas"
(
    "id_reseña" serial,
    id_pedido serial,
    id_cliente serial,
    calificacion smallint,
    comentario text,
    fecha time without time zone,
    PRIMARY KEY ("id_reseña")
);

ALTER TABLE IF EXISTS public.profesional
    ADD FOREIGN KEY (id_profesional)
    REFERENCES public."Usuario" (id_usuario) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.servicio
    ADD FOREIGN KEY (id_profesional)
    REFERENCES public.profesional (id_profesional) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Pedido"
    ADD FOREIGN KEY (id_cliente)
    REFERENCES public."Usuario" (id_usuario) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Pedido"
    ADD FOREIGN KEY (id_servicio)
    REFERENCES public.servicio (id_servicio) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.pago
    ADD FOREIGN KEY (id_pedido)
    REFERENCES public."Pedido" (id_pedido) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."reseñas"
    ADD FOREIGN KEY (id_pedido)
    REFERENCES public."Pedido" (id_pedido) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;