-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


ALTER TABLE IF EXISTS public."Pedido" DROP CONSTRAINT IF EXISTS "Pedido_id_cliente_fkey";

ALTER TABLE IF EXISTS public."Pedido" DROP CONSTRAINT IF EXISTS "Pedido_id_servicio_fkey";

ALTER TABLE IF EXISTS public.pago DROP CONSTRAINT IF EXISTS pago_id_pedido_fkey;

ALTER TABLE IF EXISTS public.profesional DROP CONSTRAINT IF EXISTS profesional_id_profesional_fkey;

ALTER TABLE IF EXISTS public.reclamaciones DROP CONSTRAINT IF EXISTS reclamaciones_id_pedido_fkey;

ALTER TABLE IF EXISTS public."reseñas" DROP CONSTRAINT IF EXISTS "reseñas_id_pedido_fkey";

ALTER TABLE IF EXISTS public.servicio DROP CONSTRAINT IF EXISTS servicio_id_profesional_fkey;



DROP TABLE IF EXISTS public." cupones";

CREATE TABLE IF NOT EXISTS public." cupones"
(
    "Id_cupon" serial NOT NULL,
    canjeado boolean,
    CONSTRAINT " cupones_pkey" PRIMARY KEY ("Id_cupon")
);

DROP TABLE IF EXISTS public."Pedido";

CREATE TABLE IF NOT EXISTS public."Pedido"
(
    id_pedido serial NOT NULL,
    id_servicio serial NOT NULL,
    id_cliente serial NOT NULL,
    fecha_contratacion time without time zone,
    estado text COLLATE pg_catalog."default",
    archivo_entraga text COLLATE pg_catalog."default",
    CONSTRAINT "Pedido_pkey" PRIMARY KEY (id_pedido)
);

DROP TABLE IF EXISTS public."Usuario";

CREATE TABLE IF NOT EXISTS public."Usuario"
(
    id_usuario serial NOT NULL,
    nombre text COLLATE pg_catalog."default",
    apellido text COLLATE pg_catalog."default",
    email text COLLATE pg_catalog."default" NOT NULL,
    "contraseña" text COLLATE pg_catalog."default",
    pic_url text COLLATE pg_catalog."default",
    rol text COLLATE pg_catalog."default",
    fecha_registro time without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "Usuario_pkey" PRIMARY KEY (id_usuario)
);

DROP TABLE IF EXISTS public.pago;

CREATE TABLE IF NOT EXISTS public.pago
(
    id_pago serial NOT NULL,
    id_pedido serial NOT NULL,
    monto integer,
    fecha_pago time without time zone,
    metodo_pago text COLLATE pg_catalog."default",
    estado text COLLATE pg_catalog."default",
    CONSTRAINT pago_pkey PRIMARY KEY (id_pago)
);

DROP TABLE IF EXISTS public.profesional;

CREATE TABLE IF NOT EXISTS public.profesional
(
    id_profesional serial NOT NULL,
    descripcion text COLLATE pg_catalog."default",
    experiencia text COLLATE pg_catalog."default",
    habilidades text COLLATE pg_catalog."default",
    calificacion_promedio double precision,
    suscripcion_premium boolean,
    CONSTRAINT profesional_pkey PRIMARY KEY (id_profesional)
);

DROP TABLE IF EXISTS public.reclamaciones;

CREATE TABLE IF NOT EXISTS public.reclamaciones
(
    id_reclamacion serial NOT NULL,
    id_pedido serial NOT NULL,
    reclamo text COLLATE pg_catalog."default",
    resuelto boolean,
    CONSTRAINT reclamaciones_pkey PRIMARY KEY (id_reclamacion)
);

DROP TABLE IF EXISTS public."reseñas";

CREATE TABLE IF NOT EXISTS public."reseñas"
(
    "id_reseña" serial NOT NULL,
    id_pedido serial NOT NULL,
    id_cliente serial NOT NULL,
    calificacion smallint,
    comentario text COLLATE pg_catalog."default",
    fecha time without time zone,
    CONSTRAINT "reseñas_pkey" PRIMARY KEY ("id_reseña")
);

DROP TABLE IF EXISTS public.servicio;

CREATE TABLE IF NOT EXISTS public.servicio
(
    id_servicio serial NOT NULL,
    id_profesional serial NOT NULL,
    titulo text COLLATE pg_catalog."default",
    descripcion text COLLATE pg_catalog."default",
    precio integer,
    tiempo_entrega integer,
    estado text COLLATE pg_catalog."default",
    destacado boolean,
    CONSTRAINT servicio_pkey PRIMARY KEY (id_servicio)
);

ALTER TABLE IF EXISTS public."Pedido"
    ADD CONSTRAINT "Pedido_id_cliente_fkey" FOREIGN KEY (id_cliente)
    REFERENCES public."Usuario" (id_usuario) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Pedido"
    ADD CONSTRAINT "Pedido_id_servicio_fkey" FOREIGN KEY (id_servicio)
    REFERENCES public.servicio (id_servicio) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.pago
    ADD CONSTRAINT pago_id_pedido_fkey FOREIGN KEY (id_pedido)
    REFERENCES public."Pedido" (id_pedido) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.profesional
    ADD CONSTRAINT profesional_id_profesional_fkey FOREIGN KEY (id_profesional)
    REFERENCES public."Usuario" (id_usuario) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;
CREATE INDEX IF NOT EXISTS profesional_pkey
    ON public.profesional(id_profesional);


ALTER TABLE IF EXISTS public.reclamaciones
    ADD CONSTRAINT reclamaciones_id_pedido_fkey FOREIGN KEY (id_pedido)
    REFERENCES public."Pedido" (id_pedido) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."reseñas"
    ADD CONSTRAINT "reseñas_id_pedido_fkey" FOREIGN KEY (id_pedido)
    REFERENCES public."Pedido" (id_pedido) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.servicio
    ADD CONSTRAINT servicio_id_profesional_fkey FOREIGN KEY (id_profesional)
    REFERENCES public.profesional (id_profesional) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;